### ISSUE TITLE
r-description issues

### ISSUE THREAD

**Issue by dpastoor** [jelmer/deb822-lossless#140]
hello! very exciting to see that someone else has taken to parsing. There are all sorts of funky edge-y cases that i have been bumbling around parsing in various ways.

I am going to look into this further as I justed tried quickly.

Here is a "real" (and extremely popular) R package description. Trying to run the following panics:

```
const DPLYR_DESC: &str = r#"
Type: Package
Package: dplyr
Title: A Grammar of Data Manipulation
Version: 1.1.4
Authors@R: c( person("Hadley", "Wickham", , "hadley@posit.co", role =
        c("aut", "cre"), comment = c(ORCID = "0000-0003-4757-117X")),
        person("Romain", "François", role = "aut", comment = c(ORCID =
        "0000-0002-2444-4226")), person("Lionel", "Henry", role = "aut"),
        person("Kirill", "Müller", role = "aut", comment = c(ORCID =
        "0000-0002-1416-3412")), person("Davis", "Vaughan", ,
        "davis@posit.co", role = "aut", comment = c(ORCID =
        "0000-0003-4777-038X")), person("Posit Software, PBC", role =
        c("cph", "fnd")) )
Description: A fast, consistent tool for working with data frame like
        objects, both in memory and out of memory.
License: MIT + file LICENSE
URL: https://dplyr.tidyverse.org, https://github.com/tidyverse/dplyr
BugReports: https://github.com/tidyverse/dplyr/issues
Depends: R (>= 3.5.0)
Imports: cli (>= 3.4.0), generics, glue (>= 1.3.2), lifecycle (>= 1.0.3),
        magrittr (>= 1.5), methods, pillar (>= 1.9.0), R6, rlang (>=
        1.1.0), tibble (>= 3.2.0), tidyselect (>= 1.2.0), utils, vctrs (>=
        0.6.4)
Suggests: bench, broom, callr, covr, DBI, dbplyr (>= 2.2.1), ggplot2,
        knitr, Lahman, lobstr, microbenchmark, nycflights13, purrr,
        rmarkdown, RMySQL, RPostgreSQL, RSQLite, stringi (>= 1.7.6),
        testthat (>= 3.1.5), tidyr (>= 1.3.0), withr
VignetteBuilder: knitr
Config/Needs/website: tidyverse, shiny, pkgdown, tidyverse/tidytemplate
Config/testthat/edition: 3
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.2.3
NeedsCompilation: yes
Packaged: 2023-11-16 21:48:56 UTC; hadleywickham
Author: Hadley Wickham [aut, cre]
        (<https://orcid.org/0000-0003-4757-117X>), Romain François [aut]
        (<https://orcid.org/0000-0002-2444-4226>), Lionel Henry [aut],
        Kirill Müller [aut] (<https://orcid.org/0000-0002-1416-3412>),
        Davis Vaughan [aut] (<https://orcid.org/0000-0003-4777-038X>),
        Posit Software, PBC [cph, fnd]
Maintainer: Hadley Wickham <hadley@posit.co>
Repository: RSPM
Date/Publication: 2023-11-17 16:50:02 UTC
Built: R 4.3.0; x86_64-pc-linux-gnu; 2023-11-20 12:40:25 UTC; unix
"#;
    
             let desc: RDescription = DPLYR_DESC.parse().unwrap();
             dbg!(desc);
```

results in 

```
thread 'main' panicked at src/main.rs:53:58:
called `Result::unwrap()` on an `Err` value: "expected ':', got Some(NEWLINE)\nexpected ':', got Some(NEWLINE)\nexpected ':', got Some(NEWLINE)\n"
```

I choose this example as there is indeed some funky wrapping that goes into some of these outputs that the r tooling generates - you can see in the imports there are line wraps between dependencies as an example.

I've been ever so slowly experimenting with parsing some of this https://github.com/A2-ai/exp-rust-rparser-tools/blob/main/rparsertools/src/rust/src/dependencies.rs and would be interested to see if its possible to take advantage of all the work you've put in here.

Would love your thoughts/impressions of the above and if you have any future plans around the existing work to assess if this is something that we could join together.

**Comment by jelmer** [comment]
Thanks for the bugreport! I haven't done a lot of tests with R description fields, but they seem to use deb822 with slightly different fields styles than Debian control files, which is highlighting some bugs here.

I've fixed an oversight in the lexer that meant some field names weren't considered valid - it should now strictly follow deb822.

The other issue appears to be that my reading of the R DESCRIPTION spec only allowed a single URL in the URL field, rather than a list separated by comma's. For the moment I've reverted this back to just a plain string that the consumer can parse further.

I've also added the description you provided as a unit test.

**Comment by jelmer** [comment]
> Would love your thoughts/impressions of the above and if you have any future plans around the existing work to assess if this is something that we could join together.

I'd like to get the parser correct and functional, but have no plans beyond that. I would like to add support for properly parsing R style relations (i.e. Imports/Depends/Recommends), in the same way that the debian-control package already does for Debian (see debian-control/src/lossy/relations.rs in this repo).

In general, I'd be keen to hear about DESCRIPTION files that the parser fails to deal with - either with PRs fixing said issues or without :)

**Comment by jelmer** [comment]
The lossy parser now also supports parsing relations strings.

**Comment by jelmer** [comment]
FWIW the R DESCRIPTION crate is now in its own repository at https://github.com/jelmer/r-description-rs
