### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by michalfita** [jelmer/deb822-lossless#182]
This repo doesn't contain license specification what makes decision whether use it or not very hard.

Please add `LICENSE.md`, ideally typical Rust's MIT+Apache 2.0 combination.

Thank you.

**Comment by jelmer** [comment]
FWIW the license is documented in Cargo.toml; I'm happy to ship a copy of the license as well.

**Comment by michalfita** [comment]
Thanks.

Now GitHub undobtfully displays the license as well.
